### ISSUE TITLE
详细设计迭代，任务说明

### ISSUE THREAD

**Issue by wantianhe** [sebuaa2020/Team105#1]
鲍韦彤 、王宇思 学习ROS，看有没有包可以用/node节点怎么编写（有思路即可）
沈佳钰 路径规划+避障详细类图+伪代码修改
刘婉婷 建图+导航详细类图+伪代码修改
校怡哲 需求文档跟进
请于周五晚提交迭代后的版本。

**Comment by 167349** [comment]
[类的类图.zip](https://github.com/sebuaa2020/Team105/files/4567690/default.zip)
